<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Amarendra" name="com.heyprescribe.testcase.PatientAppoitnmentTest" tests="42" failures="0" timestamp="4 Nov 2020 04:57:15 GMT" time="84.564" errors="40">
  <testcase name="verifyThePatientDetailOnPrescribePage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientDetailOnPrescribePage()[pri:13, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientDetailOnPrescribePage()[pri:13, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientDetailOnPrescribePage -->
  <testcase name="verifyThePatientDetailOnPdfFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientDetailOnPdfFile()[pri:19, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientDetailOnPdfFile()[pri:19, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientDetailOnPdfFile -->
  <testcase name="verifyThePatientAppointmenOnAllAppointmenPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientAppointmenOnAllAppointmenPage()[pri:11, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientAppointmenOnAllAppointmenPage()[pri:11, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientAppointmenOnAllAppointmenPage -->
  <testcase name="verifyPatientIsAbleToBookTheAppoitnment" time="26.837" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for visibility of element located by By.className: pay-text (tried for 20 second(s) with 500 milliseconds interval)">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.className: pay-text (tried for 20 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.heyprescribe.utill.WebDriverExtension.waitForElementVisible(WebDriverExtension.java:26)
	at com.heyprescribe.page.AppoitnmentConfirmation.confirmationMesage(AppoitnmentConfirmation.java:25)
	at com.heyprescribe.testcase.PatientAppoitnmentTest.verifyPatientIsAbleToBookTheAppoitnment(PatientAppoitnmentTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: .pay\-text
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMARENDRA', ip: '192.168.144.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 81.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200930150533, moz:geckodriverVersion: 0.27.0, moz:headless: false, moz:processID: 33460, moz:profile: C:\Users\amarendra.singh\Ap..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: d346b141-97fb-4a07-81d0-4b8a0f5c440a
*** Element info: {Using=class name, value=pay-text}
	at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByClassName(RemoteWebDriver.java:412)
	at org.openqa.selenium.By$ByClassName.findElement(By.java:389)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
	... 23 more
]]>
    </error>
  </testcase> <!-- verifyPatientIsAbleToBookTheAppoitnment -->
  <testcase name="verifyThePrescriptionReport" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescriptionReport()[pri:16, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescriptionReport()[pri:16, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescriptionReport -->
  <testcase name="verifyThePrescribeLogin" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescribeLogin()[pri:10, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescribeLogin()[pri:10, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescribeLogin -->
  <testcase name="verifyThePatientAppointmenOnAllAppointmenPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientAppointmenOnAllAppointmenPage()[pri:11, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientAppointmenOnAllAppointmenPage()[pri:11, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientAppointmenOnAllAppointmenPage -->
  <testcase name="verifyThePrescriptionReport" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescriptionReport()[pri:16, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescriptionReport()[pri:16, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescriptionReport -->
  <testcase name="verifythePatientDashboard" time="8.508" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyThePatientInformationOnAppoitnmentConfirmationPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientInformationOnAppoitnmentConfirmationPage()[pri:3, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientInformationOnAppoitnmentConfirmationPage()[pri:3, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientInformationOnAppoitnmentConfirmationPage -->
  <testcase name="verifyTheStatusAfterGeneratingThePrescription" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheStatusAfterGeneratingThePrescription()[pri:21, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheStatusAfterGeneratingThePrescription()[pri:21, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheStatusAfterGeneratingThePrescription -->
  <testcase name="verifyThePatientUploadedPrescriptionFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientUploadedPrescriptionFile()[pri:14, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientUploadedPrescriptionFile()[pri:14, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientUploadedPrescriptionFile -->
  <testcase name="verifyTheVideoLinkOnAppointmentConfirmationPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheVideoLinkOnAppointmentConfirmationPage()[pri:6, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheVideoLinkOnAppointmentConfirmationPage()[pri:6, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheVideoLinkOnAppointmentConfirmationPage -->
  <testcase name="verifyTheSucesMsgAfterUploadingTheFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheSucesMsgAfterUploadingTheFile()[pri:8, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheSucesMsgAfterUploadingTheFile()[pri:8, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheSucesMsgAfterUploadingTheFile -->
  <testcase name="verifyThePrescriptionReportDownloadLink" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescriptionReportDownloadLink()[pri:18, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescriptionReportDownloadLink()[pri:18, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescriptionReportDownloadLink -->
  <testcase name="verifyTheSucesMsgAfterUploadingTheFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheSucesMsgAfterUploadingTheFile()[pri:8, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheSucesMsgAfterUploadingTheFile()[pri:8, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheSucesMsgAfterUploadingTheFile -->
  <testcase name="verifyThePrescriptionDetailOnPdfFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescriptionDetailOnPdfFile()[pri:20, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescriptionDetailOnPdfFile()[pri:20, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescriptionDetailOnPdfFile -->
  <testcase name="verifyTheDoctorNameOnAppoitnmentConfirmationpage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheDoctorNameOnAppoitnmentConfirmationpage()[pri:4, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheDoctorNameOnAppoitnmentConfirmationpage()[pri:4, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheDoctorNameOnAppoitnmentConfirmationpage -->
  <testcase name="verifyTheDateAndSlotOnAppointmentConfirmationPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheDateAndSlotOnAppointmentConfirmationPage()[pri:5, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheDateAndSlotOnAppointmentConfirmationPage()[pri:5, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheDateAndSlotOnAppointmentConfirmationPage -->
  <testcase name="verifyThePatientDetailOnPdfFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientDetailOnPdfFile()[pri:19, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientDetailOnPdfFile()[pri:19, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientDetailOnPdfFile -->
  <testcase name="verifyPatientIsAbleToBookTheAppoitnment" time="27.260" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for visibility of element located by By.className: pay-text (tried for 20 second(s) with 500 milliseconds interval)">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.className: pay-text (tried for 20 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.heyprescribe.utill.WebDriverExtension.waitForElementVisible(WebDriverExtension.java:26)
	at com.heyprescribe.page.AppoitnmentConfirmation.confirmationMesage(AppoitnmentConfirmation.java:25)
	at com.heyprescribe.testcase.PatientAppoitnmentTest.verifyPatientIsAbleToBookTheAppoitnment(PatientAppoitnmentTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".pay\-text"}
  (Session info: chrome=86.0.4240.111)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMARENDRA', ip: '192.168.144.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 86.0.4240.111, chrome: {chromedriverVersion: 86.0.4240.22 (398b0743353ff..., userDataDir: C:\Users\amarendra.singh\Ap...}, goog:chromeOptions: {debuggerAddress: localhost:54813}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 803a9733d4b20e32dd63c8f682a0ad3f
*** Element info: {Using=class name, value=pay-text}
	at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByClassName(RemoteWebDriver.java:412)
	at org.openqa.selenium.By$ByClassName.findElement(By.java:389)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
	... 23 more
]]>
    </error>
  </testcase> <!-- verifyPatientIsAbleToBookTheAppoitnment -->
  <testcase name="verifyThePatientInformationOnAppoitnmentConfirmationPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientInformationOnAppoitnmentConfirmationPage()[pri:3, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientInformationOnAppoitnmentConfirmationPage()[pri:3, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientInformationOnAppoitnmentConfirmationPage -->
  <testcase name="verifyTheGeneratePrescriptionReportFunctionality" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheGeneratePrescriptionReportFunctionality()[pri:17, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheGeneratePrescriptionReportFunctionality()[pri:17, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheGeneratePrescriptionReportFunctionality -->
  <testcase name="verifyThePrescriptionReportDownloadLink" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescriptionReportDownloadLink()[pri:18, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescriptionReportDownloadLink()[pri:18, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescriptionReportDownloadLink -->
  <testcase name="verifyTheDoctorNameOnAppoitnmentConfirmationpage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheDoctorNameOnAppoitnmentConfirmationpage()[pri:4, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheDoctorNameOnAppoitnmentConfirmationpage()[pri:4, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheDoctorNameOnAppoitnmentConfirmationpage -->
  <testcase name="verifyTheEmailConfirmationOnGmail" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheEmailConfirmationOnGmail()[pri:9, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheEmailConfirmationOnGmail()[pri:9, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheEmailConfirmationOnGmail -->
  <testcase name="verifythePatientDashboard" time="21.959" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyTheConnectToVideoPopUpOnPrescribePage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheConnectToVideoPopUpOnPrescribePage()[pri:12, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheConnectToVideoPopUpOnPrescribePage()[pri:12, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheConnectToVideoPopUpOnPrescribePage -->
  <testcase name="verifyTheUploadedFileOnAppointmentConfirmationPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheUploadedFileOnAppointmentConfirmationPage()[pri:7, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheUploadedFileOnAppointmentConfirmationPage()[pri:7, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheUploadedFileOnAppointmentConfirmationPage -->
  <testcase name="verifyTheConnectToVideoPopUpOnPrescribePage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheConnectToVideoPopUpOnPrescribePage()[pri:12, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheConnectToVideoPopUpOnPrescribePage()[pri:12, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheConnectToVideoPopUpOnPrescribePage -->
  <testcase name="saveThePhysicianPrescription" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.saveThePhysicianPrescription()[pri:15, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.saveThePhysicianPrescription()[pri:15, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- saveThePhysicianPrescription -->
  <testcase name="verifyThePrescriptionDetailOnPdfFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescriptionDetailOnPdfFile()[pri:20, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescriptionDetailOnPdfFile()[pri:20, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescriptionDetailOnPdfFile -->
  <testcase name="verifyThePatientDetailOnPrescribePage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientDetailOnPrescribePage()[pri:13, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientDetailOnPrescribePage()[pri:13, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientDetailOnPrescribePage -->
  <testcase name="saveThePhysicianPrescription" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.saveThePhysicianPrescription()[pri:15, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.saveThePhysicianPrescription()[pri:15, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- saveThePhysicianPrescription -->
  <testcase name="verifyTheDateAndSlotOnAppointmentConfirmationPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheDateAndSlotOnAppointmentConfirmationPage()[pri:5, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheDateAndSlotOnAppointmentConfirmationPage()[pri:5, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheDateAndSlotOnAppointmentConfirmationPage -->
  <testcase name="verifyTheVideoLinkOnAppointmentConfirmationPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheVideoLinkOnAppointmentConfirmationPage()[pri:6, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheVideoLinkOnAppointmentConfirmationPage()[pri:6, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheVideoLinkOnAppointmentConfirmationPage -->
  <testcase name="verifyTheUploadedFileOnAppointmentConfirmationPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheUploadedFileOnAppointmentConfirmationPage()[pri:7, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheUploadedFileOnAppointmentConfirmationPage()[pri:7, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheUploadedFileOnAppointmentConfirmationPage -->
  <testcase name="verifyThePrescribeLogin" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescribeLogin()[pri:10, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescribeLogin()[pri:10, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescribeLogin -->
  <testcase name="verifyTheStatusAfterGeneratingThePrescription" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheStatusAfterGeneratingThePrescription()[pri:21, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheStatusAfterGeneratingThePrescription()[pri:21, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheStatusAfterGeneratingThePrescription -->
  <testcase name="verifyThePatientUploadedPrescriptionFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientUploadedPrescriptionFile()[pri:14, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientUploadedPrescriptionFile()[pri:14, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@5123a213] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientUploadedPrescriptionFile -->
  <testcase name="verifyTheEmailConfirmationOnGmail" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheEmailConfirmationOnGmail()[pri:9, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheEmailConfirmationOnGmail()[pri:9, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheEmailConfirmationOnGmail -->
  <testcase name="verifyTheGeneratePrescriptionReportFunctionality" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheGeneratePrescriptionReportFunctionality()[pri:17, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheGeneratePrescriptionReportFunctionality()[pri:17, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@15bfd87] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheGeneratePrescriptionReportFunctionality -->
</testsuite> <!-- com.heyprescribe.testcase.PatientAppoitnmentTest -->
